### ISSUE TITLE
[NEWPROVIDER] - Xentain Solutions

### ISSUE THREAD

**Issue by Plactrix** [bgpcheap/website#17]
### Provider Name

Xentain Solutions

### Provider URL

https://xentain.com

### Provider ASN

AS15353

### BGP Communities

Route origin (Where the route originated from)

### BGP Communities Pass-through

Yes

### Automatic Prefix List

Yes

### How often are the filters updated? (If available)

24h

### RPKI Filtering

Yes

### LOA Required

No

### IPv6 Support

Yes

### What type of BGP tables can you provide?

Full Table

### Locations

1. Dallas, Texas
2. Fremont, California
3. Vancouver, British Columbia
4. Beauharnois, Quebec

### Services offered

1. VPS
2. Baremetal
3. Colocation
4. IXP Access
5. IP Transit

### Downstream Support (AS-SET)

Yes

### Notes

IPv6 included free
Starting at $1.25/mo for VPS, starting at $45/mo for baremetal
Free BGP in Dallas, Vancouver, and Fremont
UNM-Exch (unmetered.exchange) ports available for Vancouver services

### Policy

- [X] I agree that the provider falls within this policy

**Comment by yoitszigi** [comment]
Will be added shortly

**Comment by baragoon** [comment]
Wrong URL on the site, please fix.
