### ISSUE TITLE
[HostHatch] - <HostHatch>

### ISSUE THREAD

**Issue by abdullah-hh** [bgpcheap/website#20]
### Provider Name

HostHatch

### Provider URL

hosthatch.com

### Provider ASN

AS63473

### BGP Communities

No communities

### BGP Communities Pass-through

Yes

### Automatic Prefix List

No

### RPKI Filtering

Yes

### LOA Required

Yes

### IPv6 Support

Yes

### What type of BGP tables can you provide?

Default

### Locations

1. Amsterdam
2. Vienna
3. Stockholm
4. Zurich
5. Los Angeles
6. New York
7. Chicago
8. Hong Kong
9. Tokyo
10. Sydney
11. Singapore
12. London
13. Oslo
...

### Services offered

1. VM hosting
2.
3.
...

### Downstream Support (AS-SET)

No

### Policy

- [X] I agree that the provider falls within this policy

**Comment by yoitszigi** [comment]
@abdullah-hh Last I heard, HostHatch has a BGP fee. Is this correct?

**Comment by abdullah-hh** [comment]
HostHatch charges a $10 USD setup fee for BGP, no monthly or any other fees.

**Comment by yoitszigi** [comment]
> @yoitszigi HostHatch charges a $10 USD setup fee for BGP, no monthly or any other fees.

Ah, I am going off what I was last told by HostHatch. I assume you work for HostHatch?

**Comment by yoitszigi** [comment]
> > > @yoitszigi HostHatch charges a $10 USD setup fee for BGP, no monthly or any other fees.
> > 
> > 
> > Ah, I am going off what I was last told by HostHatch. I assume you work for HostHatch?
> 
> Yes :)

Gotcha. I'll adjust it for you. Thanks for the updated information
