### ISSUE TITLE
[NEWPROVIDER] - Servperso

### ISSUE THREAD

**Issue by baragoon** [bgpcheap/website#28]
### Provider Name

Servperso

### Provider URL

https://www.servperso.net/bgp-vm

### Provider ASN

AS34872

### BGP Communities

Route origin (Where the route originated from)

### BGP Communities Pass-through

Yes

### Automatic Prefix List

Yes

### RPKI Filtering

Yes

### LOA Required

No

### IPv6 Support

Yes

### What type of BGP tables can you provide?

Full Table, Full Table + Default, Default

### Locations

1. Meppel
2. Dusseldorf
3.
...

### Services offered

1. VPS
2. Tunnel
3. Transit (both free & pay)
4. IX connection (LocIX-Fra, LocIX-Dus, LocIX-NL are confirmed)
...

### Downstream Support (AS-SET)

Yes

### Notes

Starting from 10€
Setup fee 10€
no BGP fee

### Policy

- [X] I agree that the provider falls within this policy

**Comment by servperso** [comment]
Hi @yoitszigi
,
Any issue regarding this provider prupose ?

Best regards,

**Comment by yoitszigi** [comment]
Added in commit

[dafb9de](https://github.com/bgpcheap/website/commit/dafb9deb3bc1e8b13d6d37e106a4edd23e23c652) #
