### ISSUE TITLE
[NEWPROVIDER] - Fibersix

### ISSUE THREAD

**Issue by ascionefrancesco** [bgpcheap/website#31]
### Provider Name

Fibersix

### Provider URL

https://fibersix.it/

### Provider ASN

47152

### BGP Communities

No communities

### BGP Communities Pass-through

Yes

### Automatic Prefix List

Yes

### How often are the filters updated? (If available)

12h

### RPKI Filtering

Yes

### LOA Required

No

### IPv6 Support

Yes

### What type of BGP tables can you provide?

Full Table + Default

### Locations

1. Salerno, IT

### Services offered

1. Virtual Private Server
2. Dedicated server
3. Colocation

### Downstream Support (AS-SET)

Yes

### Notes

Virtual Private Server starts from 7 EUR/mo
Free BGP session on Italian bandwidth

### Policy

- [X] I agree that the provider falls within this policy

**Comment by yoitszigi** [comment]
Rejected.
