### ISSUE TITLE
[NEWPROVIDER] - Civilized Hosting LLC

### ISSUE THREAD

**Issue by iambrayden0** [bgpcheap/website#38]
### Provider Name

Civilized Hosting LLC

### Provider URL

https://civilizedhosting.net

### Provider ASN

AS216360

### BGP Communities

No communities

### BGP Communities Pass-through

Yes

### Automatic Prefix List

Yes

### RPKI Filtering

Yes

### LOA Required

No

### IPv6 Support

Yes

### What type of BGP tables can you provide?

Full Table

### Locations

1. Kansas City, MO

### Services offered

1. BGP VMs
2. Colocation
3. Dedicated Servers
4. VPS
5. Website Hosting
6. IP Transit
7. IP Subnets

### Downstream Support (AS-SET)

Yes

### Policy

- [X] I agree that the provider falls within this policy

**Comment by yoitszigi** [comment]
Hi Brayden,

Unfortunately, your business does not suit our requirements to be listed on the website. Due to recent events we are going to reject on adding you to the website for now

-Zigi
