### ISSUE TITLE
[NEWPROVIDER] - SYSTEM36

### ISSUE THREAD

**Issue by ziad8727** [bgpcheap/website#40]
### Provider Name

SYSTEM36

### Provider URL

https://36.services/

### Provider ASN

59678

### BGP Communities

No communities

### BGP Communities Pass-through

Yes

### Automatic Prefix List

Yes

### How often are the filters updated? (If available)

Every 6 hours (Upstreams may take longer)

### RPKI Filtering

Yes

### LOA Required

No

### IPv6 Support

Yes

### What type of BGP tables can you provide?

Full Table, Full Table + Default, Default

### Locations

1. Piscataway, NJ, US

### Services offered

1. VPS
2. Dedicated Servers

### Downstream Support (AS-SET)

Yes

### Policy

- [X] I agree that the provider falls within this policy

**Comment by yoitszigi** [comment]
@ziad8727 Do you have a dark logo we can use on our website?
