### ISSUE TITLE
[NEWPROVIDER] - MyHostingSpace

### ISSUE THREAD

**Issue by chrisbish** [bgpcheap/website#41]
### Provider Name

MyHostingSpace

### Provider URL

https://myhostingspace.co.uk

### Provider ASN

48070

### BGP Communities

Traffic Engineering (Prepends / Do not announce), Route origin (Where the route originated from)

### Link to BGP communities (if available)

https://as48070.net/our-network/

### BGP Communities Pass-through

Yes

### Automatic Prefix List

Yes

### RPKI Filtering

Yes

### LOA Required

Yes

### IPv6 Support

Yes

### What type of BGP tables can you provide?

Full Table, Full Table + Default, Default

### Locations

1. Peterborough, United Kingdom
2.
3.
...

### Services offered

1. Dedicated Servers
2. Virtual Servers
3. Colocation & Rackspace
...

### Downstream Support (AS-SET)

Yes

### Policy

- [X] I agree that the provider falls within this policy

**Comment by yoitszigi** [comment]
Hi @chrisbish 

Do you have a dark logo we can use on the website?

**Comment by chrisbish** [comment]
![mhs-logo-blue-400](https://github.com/bgpcheap/website/assets/1550232/1afd025c-faa2-46a8-a78e-f11b2fb56aef)
![mhs-logo-white-400px](https://github.com/bgpcheap/website/assets/1550232/0999823c-90ce-434e-aa92-bb8ac68e730a)

Attached Logos.
