### ISSUE TITLE
[UPDATEPROVIDER] - Servperso

### ISSUE THREAD

**Issue by servperso** [bgpcheap/website#69]
### Provider Name

Servperso

### What needs updating?

1. Minimum price range: 4€ for vm, 6€ for tunnel
2. Fullview type: full or default
3.
...

**Comment by baragoon** [comment]
@servperso no price change for existing customers?

**Comment by servperso** [comment]
No, because both offers are not the same. We mainly create "more choice" and more accessible offer.
It's still possible to migrate but it's up to you to see if it's better for you to do or to keep old offer.
