### ISSUE TITLE
[NEWPROVIDER] -  GetServers

### ISSUE THREAD

**Issue by yoitszigi** [bgpcheap/website#9]
### Provider Name

GetServers

### Provider URL

https://getservers.co.uk/

### Provider ASN

48605

### BGP Communities

Traffic Engineering (Prepends / Do not announce), Route origin (Where the route originated from)

### Link to BGP communities (if available)

https://as48605.net/

### BGP Communities Pass-through

Yes

### Automatic Prefix List

Yes

### RPKI Filtering

Yes

### LOA Required

Yes

### IPv6 Support

Yes

### What type of BGP tables can you provide?

Full Table + Default

### Locations

1. Manchester, GB

### Services offered

1. VPS
2. Baremetal

### Downstream Support (AS-SET)

Yes

### Policy

- [X] I agree that the provider falls within this policy

**Comment by baragoon** [comment]
Received an email about Company Closure and Service Termination

We are writing to inform you that 27Fibre Ltd the company behind GetServers will be entering into liquidation, as a result we will be shutting down all hosting services effective the 30th of June 2024.

We kindly request that you remove all your data from our systems by the 30th of June 2024 as after this date you will no longer have access to your servers/data, and we will not be able to extend your service or recover any information after this date.
